<h1 id="title">Python 异常之后不知多少行的解决办法</h1>
<time id="date" datetime="2016-06-01T01:14:09+08:00">2016-06-01 01:14</time>
<section id="content">
    <p>用try&nbsp;except之后，抛出的错误却不知道第几行，有时候着实让人着急</p>
    <p>解决这个办法要使用 traceback 来跟踪错误</p>
    <p>常见如下</p>
    <p>
        [cc lang=”php”]<br />try:<br />print dddd<br />except Exception, e:<br />print
        e<br />[/cc]
    </p>
    <p>这样子的代码只是输出了错误的主要信息，并没有输出你错误的地点</p>
    <p>使用traceback</p>
    <p>
        [cc lang=”php”]<br />try:<br />print dddd<br />except Exception, e:<br />traceback.print_exc()<br />[/cc]
    </p>
    <p>这样就能够知道代码错误到底在第几行，以便于我们修改错误。</p>
    <div class="entry-copyright">
        <p>
            原创文章，作者：老D，如若转载，请注明出处：https://laod.cn/code-audit/python-abnormal.html
        </p>
    </div>
</section>
